[project]
name = "mon_app"
version = "0.1.0"
dependencies = [
    "streamlit"
]
requires-python = "3.9"

[build-system]
requires = ["setuptoools", "wheel"]
build-backend = "setuptools.build_meta"